[project]
org-name= "dehami"
version= "0.1.0"

[dependencies]

[platform]
target = "java8"

[[platform.libraries]]
    artafactId = "mysql-connector-java"
    version = "5.1.48"
    path = "./dependencies/mysql-connector-java-5.1.48.jar"
    groupId = "mysql"
    modules = ["manage_students"]